spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/airline_user_service
    username: root
    password: mysql@123

  jpa:
    hibernate:
      ddl-auto: update      # use 'validate' or 'none' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 5005

app:
  jwt:
    secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007

    expiry-ms: 600000